### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by maradotwebp** [MinecraftMachina/cornstone#1]
Hey, quick question: What problems is this tool trying to solve? I just found out about this github through thevortex, and it seems like we both starting developing a mc modpack development tool with the same purpose at almost the same time. I can't quite tell from the readme, but if you're also developing a tool to make creating & maintaining minecraft modpacks easier, maybe we should team up and develop one together.

Here's my project: https://github.com/froehlichA/pax

**Comment by ViRb3** [comment]
Hello! That's an awesome project you have there. Yes, it does seem like we are both trying to do the same thing. I have sent you an e-mail to discuss a collaboration further.
